-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analises_credito (
  id integer NOT NULL DEFAULT nextval('analises_credito_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  cliente_id integer NOT NULL,
  tipo_analise character varying NOT NULL,
  valor_solicitado numeric NOT NULL,
  modalidade_solicitada character varying NOT NULL,
  decisao character varying NOT NULL CHECK (decisao::text = ANY (ARRAY['Aprovado'::character varying, 'Negado'::character varying, 'Pendente'::character varying, 'Aprovado Condicional'::character varying]::text[])),
  valor_aprovado numeric,
  taxa_aprovada numeric,
  prazo_aprovado integer,
  fatores_aprovacao jsonb,
  fatores_negacao jsonb,
  condicoes jsonb,
  score_calculado integer,
  probabilidade_inadimplencia numeric,
  modelo_usado character varying,
  analista_responsavel character varying,
  data_analise timestamp with time zone NOT NULL,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analises_credito_pkey PRIMARY KEY (id),
  CONSTRAINT analises_credito_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.clientes (
  id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  tipo_pessoa character varying NOT NULL CHECK (tipo_pessoa::text = ANY (ARRAY['PF'::character varying, 'PJ'::character varying]::text[])),
  nome character varying NOT NULL,
  cpf_cnpj character varying NOT NULL UNIQUE,
  data_nascimento date,
  renda_mensal numeric,
  profissao character varying,
  estado_civil character varying,
  escolaridade character varying,
  data_fundacao date,
  faturamento_anual numeric,
  setor character varying,
  porte character varying,
  cnae character varying,
  uf character varying NOT NULL,
  cidade character varying,
  cep character varying,
  endereco text,
  telefone character varying,
  email character varying,
  score_credito integer CHECK (score_credito >= 0 AND score_credito <= 1000),
  classe_risco character varying DEFAULT 'AA'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ativo boolean DEFAULT true,
  CONSTRAINT clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.historico_pagamentos (
  id integer NOT NULL DEFAULT nextval('historico_pagamentos_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  operacao_id integer NOT NULL,
  numero_parcela integer,
  data_vencimento date NOT NULL,
  data_pagamento date,
  valor_parcela numeric NOT NULL,
  valor_pago numeric,
  valor_juros numeric,
  valor_principal numeric,
  dias_atraso integer DEFAULT 0,
  status character varying DEFAULT 'Pendente'::character varying CHECK (status::text = ANY (ARRAY['Pendente'::character varying, 'Pago'::character varying, 'Atrasado'::character varying, 'Renegociado'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historico_pagamentos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_pagamentos_operacao_id_fkey FOREIGN KEY (operacao_id) REFERENCES public.operacoes_credito(id)
);
CREATE TABLE public.modalidades_credito (
  id integer NOT NULL DEFAULT nextval('modalidades_credito_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  nome character varying NOT NULL UNIQUE,
  categoria character varying NOT NULL,
  taxa_minima numeric,
  taxa_maxima numeric,
  prazo_minimo integer,
  prazo_maximo integer,
  valor_minimo numeric,
  valor_maximo numeric,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modalidades_credito_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operacoes_credito (
  id integer NOT NULL DEFAULT nextval('operacoes_credito_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  cliente_id integer NOT NULL,
  modalidade character varying NOT NULL,
  sub_modalidade character varying,
  valor_contratado numeric NOT NULL,
  valor_liberado numeric,
  valor_saldo numeric DEFAULT 0,
  data_contratacao date NOT NULL,
  data_primeiro_vencimento date,
  data_vencimento date,
  data_liquidacao date,
  prazo_meses integer,
  taxa_juros_mensal numeric,
  taxa_juros_anual numeric,
  indexador character varying,
  forma_pagamento character varying,
  status character varying DEFAULT 'Ativo'::character varying CHECK (status::text = ANY (ARRAY['Ativo'::character varying, 'Liquidado'::character varying, 'Vencido'::character varying, 'Baixado'::character varying]::text[])),
  classificacao_risco character varying DEFAULT 'AA'::character varying,
  dias_atraso integer DEFAULT 0,
  tipo_garantia character varying,
  valor_garantia numeric,
  origem_recurso character varying,
  instituicao_origem character varying,
  agencia character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT operacoes_credito_pkey PRIMARY KEY (id),
  CONSTRAINT operacoes_credito_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.score_historico (
  id integer NOT NULL DEFAULT nextval('score_historico_id_seq'::regclass),
  uuid uuid DEFAULT uuid_generate_v4() UNIQUE,
  cliente_id integer NOT NULL,
  score_anterior integer,
  score_atual integer NOT NULL,
  data_calculo date NOT NULL,
  fatores_impacto ARRAY,
  score_pagamento integer,
  score_historico integer,
  score_utilizacao integer,
  score_diversificacao integer,
  score_tempo integer,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT score_historico_pkey PRIMARY KEY (id),
  CONSTRAINT score_historico_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);